[package]
name = "impala-bridge"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
axum = { version = "0.4", features = ["headers"] }
tokio = { version = "1.0", features = ["full"] }
bcrypt = "0.10"
headers = "0.3"
jsonwebtoken = "7.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "uuid"] }
password-auth = { version = "1.0", features = ["argon2"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls", "stream"], default-features = false }
redis = { version = "0.23", features = ["tokio-comp"] }
chrono = "0.4"
futures = "0.3"
log = "0.4"
syslog = "6.1"
ldap3 = "0.11"

[build-dependencies]
chrono = "0.4"
