[package]
name = "impala-testnet-tests"
version = "0.0.1"
edition = "2021"
rust-version = "1.89.0"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rand = "0.8"
